dist:     trusty    # используем Ubuntu 14.04 Trusty Tahr (а не 12.02 Precise Pangolin)
sudo:     false

language: cpp

os:
    - linux

compiler:
    - gcc

addons:
  apt:
    sources:
    packages:
        - g++-4.9

script:
    # скрипт сборки и тестирования проекта:
    - mkdir build
    - cd build
    - cmake ..
    - make
    - ctest --output-on-failure

deploy:
    # выкладываем tagged-коммиты на GitHub Releases:
    provider:     releases
    file:         EBP
    skip_cleanup: true
    overwrite:    true

    api_key:
        secure:   <encrypted-github-token>

    on:
        tags:     true
